/*
 cSpell:ignore publicacion ubicacion operacion
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screens.Principal;

import Screens.Custom.CambiarIU;
import Screens.Login.Login;
import Screens.Principal.Games.Bingo;
import Screens.Principal.Games.BlackJack;
import Screens.Principal.Games.Dados;
import Screens.Principal.Games.Poker;
import Screens.Principal.Games.Ruleta;
import Screens.Principal.Games.TragaMonedas;
import Screens.Profile.PersonalProfile;

import java.awt.EventQueue;
import java.awt.Toolkit;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;

/**
 *
 * @author tutaa
 */
// TODO: poner chats en cada juego y con ia generar mensajes automaticos
public class Principal extends javax.swing.JFrame {

        /**
         * Creates new form Principal
         */
        public Principal() {
                initComponents();

                this.setTitle("Pantalla Principal");
                this.setResizable(false);
                this.setLocationRelativeTo(null);

                this.setIconImage(Toolkit.getDefaultToolkit()
                                .getImage(getClass().getResource("/img/icon.png")));
                textosLabels();

        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                ventanaPrincipal = new javax.swing.JPanel();
                panelMenu = new javax.swing.JPanel();
                imgCasa = new javax.swing.JLabel();
                imgVolver = new javax.swing.JLabel();
                imgUsuario = new javax.swing.JLabel();
                imgMenuBar = new javax.swing.JLabel();
                lbJuegos = new javax.swing.JLabel();
                scrollPublicaciones = new Screens.Custom.ScrollPaneWin11();
                panelPublicaciones = new javax.swing.JPanel();
                panelPoker = new javax.swing.JPanel();
                btnPoker = new javax.swing.JButton();
                imgPoker = new javax.swing.JLabel();
                panelRuleta = new javax.swing.JPanel();
                btnRuleta = new javax.swing.JButton();
                imgRuleta = new javax.swing.JLabel();
                panelBlackJack = new javax.swing.JPanel();
                btnBlackJack = new javax.swing.JButton();
                imgBlackJack = new javax.swing.JLabel();
                panelTragaMonedas = new javax.swing.JPanel();
                btnTragaMonedas = new javax.swing.JButton();
                imgTragaMonedas = new javax.swing.JLabel();
                panelDados = new javax.swing.JPanel();
                imgDados = new javax.swing.JLabel();
                btnDados = new javax.swing.JButton();
                panelBingo = new javax.swing.JPanel();
                btnBingo = new javax.swing.JButton();
                imgBingo = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                ventanaPrincipal.setBackground(new java.awt.Color(27, 9, 5));
                ventanaPrincipal.setPreferredSize(new java.awt.Dimension(1080, 720));
                ventanaPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                panelMenu.setBackground(new java.awt.Color(22, 22, 26));
                panelMenu.setOpaque(false);
                panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                imgCasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/casaHover.png"))); // NOI18N
                imgCasa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                panelMenu.add(imgCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

                imgVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver.png"))); // NOI18N
                imgVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                imgVolver.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                imgVolverMouseClicked(evt);
                        }

                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                imgVolverMouseEntered(evt);
                        }

                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                imgVolverMouseExited(evt);
                        }
                });
                panelMenu.add(imgVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

                imgUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
                imgUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                imgUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                imgUsuarioMouseClicked(evt);
                        }

                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                imgUsuarioMouseEntered(evt);
                        }

                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                imgUsuarioMouseExited(evt);
                        }
                });
                panelMenu.add(imgUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

                imgMenuBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                imgMenuBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lineaVertical.png"))); // NOI18N
                imgMenuBar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                panelMenu.add(imgMenuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, -1));

                ventanaPrincipal.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 230, 60, 220));

                lbJuegos.setFont(new java.awt.Font("Crabs", 1, 100)); // NOI18N
                lbJuegos.setForeground(new java.awt.Color(227, 199, 104));
                lbJuegos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbJuegos.setText("Juegos");
                ventanaPrincipal.add(lbJuegos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1080, -1));

                panelPublicaciones.setBackground(new java.awt.Color(36, 38, 41));
                panelPublicaciones.setBorder(
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 199, 104)));
                panelPublicaciones.setMinimumSize(new java.awt.Dimension(350, 100000));
                panelPublicaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                panelPoker.setBackground(new java.awt.Color(227, 199, 104));
                panelPoker.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)),
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255))));

                btnPoker.setBackground(new java.awt.Color(147, 128, 67));
                btnPoker.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnPoker.setForeground(new java.awt.Color(255, 255, 255));
                btnPoker.setText("POKER");
                btnPoker.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnPokerActionPerformed(evt);
                        }
                });

                imgPoker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/poker.png"))); // NOI18N

                javax.swing.GroupLayout panelPokerLayout = new javax.swing.GroupLayout(panelPoker);
                panelPoker.setLayout(panelPokerLayout);
                panelPokerLayout.setHorizontalGroup(
                                panelPokerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panelPokerLayout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(imgPoker,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                195,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(13, Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPokerLayout
                                                                .createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(btnPoker)
                                                                .addGap(76, 76, 76)));
                panelPokerLayout.setVerticalGroup(
                                panelPokerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panelPokerLayout.createSequentialGroup()
                                                                .addGap(15, 15, 15)
                                                                .addComponent(imgPoker,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                130,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnPoker)
                                                                .addContainerGap()));

                panelPublicaciones.add(panelPoker, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 230, 180));

                panelRuleta.setBackground(new java.awt.Color(227, 199, 104));
                panelRuleta.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)),
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255))));

                btnRuleta.setBackground(new java.awt.Color(147, 128, 67));
                btnRuleta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnRuleta.setForeground(new java.awt.Color(255, 255, 255));
                btnRuleta.setText("RULETA");
                btnRuleta.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRuletaActionPerformed(evt);
                        }
                });

                imgRuleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ruleta.png"))); // NOI18N
                imgRuleta.setText("jLabel2");

                javax.swing.GroupLayout panelRuletaLayout = new javax.swing.GroupLayout(panelRuleta);
                panelRuleta.setLayout(panelRuletaLayout);
                panelRuletaLayout.setHorizontalGroup(
                                panelRuletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panelRuletaLayout.createSequentialGroup()
                                                                .addGroup(panelRuletaLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(panelRuletaLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(72, 72, 72)
                                                                                                .addComponent(btnRuleta))
                                                                                .addGroup(panelRuletaLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(17, 17, 17)
                                                                                                .addComponent(imgRuleta,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                195,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(14, Short.MAX_VALUE)));
                panelRuletaLayout.setVerticalGroup(
                                panelRuletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRuletaLayout
                                                                .createSequentialGroup()
                                                                .addContainerGap(11, Short.MAX_VALUE)
                                                                .addComponent(imgRuleta,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                130,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnRuleta)
                                                                .addContainerGap()));

                panelPublicaciones.add(panelRuleta,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 230, 180));

                panelBlackJack.setBackground(new java.awt.Color(227, 199, 104));
                panelBlackJack.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)),
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255))));

                btnBlackJack.setBackground(new java.awt.Color(147, 128, 67));
                btnBlackJack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnBlackJack.setForeground(new java.awt.Color(255, 255, 255));
                btnBlackJack.setText("BLACKJACK");
                btnBlackJack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBlackJackActionPerformed(evt);
                        }
                });

                imgBlackJack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/blackJack.png"))); // NOI18N
                imgBlackJack.setText("jLabel2");

                javax.swing.GroupLayout panelBlackJackLayout = new javax.swing.GroupLayout(panelBlackJack);
                panelBlackJack.setLayout(panelBlackJackLayout);
                panelBlackJackLayout.setHorizontalGroup(
                                panelBlackJackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panelBlackJackLayout.createSequentialGroup()
                                                                .addGroup(panelBlackJackLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(panelBlackJackLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(72, 72, 72)
                                                                                                .addComponent(btnBlackJack))
                                                                                .addGroup(panelBlackJackLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(imgBlackJack,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                195,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(13, Short.MAX_VALUE)));
                panelBlackJackLayout.setVerticalGroup(
                                panelBlackJackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                panelBlackJackLayout.createSequentialGroup()
                                                                                .addContainerGap(11, Short.MAX_VALUE)
                                                                                .addComponent(imgBlackJack,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                130,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(btnBlackJack)
                                                                                .addContainerGap()));

                panelPublicaciones.add(panelBlackJack,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 230, 180));

                panelTragaMonedas.setBackground(new java.awt.Color(227, 199, 104));
                panelTragaMonedas.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)),
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255))));

                btnTragaMonedas.setBackground(new java.awt.Color(147, 128, 67));
                btnTragaMonedas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnTragaMonedas.setForeground(new java.awt.Color(255, 255, 255));
                btnTragaMonedas.setText("TRAGA MONEDAS");
                btnTragaMonedas.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnTragaMonedasActionPerformed(evt);
                        }
                });

                imgTragaMonedas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tragaMonedas.png"))); // NOI18N
                imgTragaMonedas.setText("jLabel2");

                javax.swing.GroupLayout panelTragaMonedasLayout = new javax.swing.GroupLayout(panelTragaMonedas);
                panelTragaMonedas.setLayout(panelTragaMonedasLayout);
                panelTragaMonedasLayout.setHorizontalGroup(
                                panelTragaMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panelTragaMonedasLayout.createSequentialGroup()
                                                                .addContainerGap(15, Short.MAX_VALUE)
                                                                .addGroup(panelTragaMonedasLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                panelTragaMonedasLayout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(imgTragaMonedas,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                195,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(16, 16, 16))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                panelTragaMonedasLayout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(btnTragaMonedas)
                                                                                                                .addGap(47, 47, 47)))));
                panelTragaMonedasLayout.setVerticalGroup(
                                panelTragaMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                panelTragaMonedasLayout.createSequentialGroup()
                                                                                .addContainerGap(11, Short.MAX_VALUE)
                                                                                .addComponent(imgTragaMonedas,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                130,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(btnTragaMonedas)
                                                                                .addContainerGap()));

                panelPublicaciones.add(panelTragaMonedas,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 230, 180));

                panelDados.setBackground(new java.awt.Color(227, 199, 104));
                panelDados.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)),
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255))));

                imgDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dados.png"))); // NOI18N
                imgDados.setText("jLabel2");

                btnDados.setBackground(new java.awt.Color(147, 128, 67));
                btnDados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnDados.setForeground(new java.awt.Color(255, 255, 255));
                btnDados.setText("DADOS");
                btnDados.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDadosActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout panelDadosLayout = new javax.swing.GroupLayout(panelDados);
                panelDados.setLayout(panelDadosLayout);
                panelDadosLayout.setHorizontalGroup(
                                panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panelDadosLayout.createSequentialGroup()
                                                                .addGroup(panelDadosLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(panelDadosLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(80, 80, 80)
                                                                                                .addComponent(btnDados))
                                                                                .addGroup(panelDadosLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(16, 16, 16)
                                                                                                .addComponent(imgDados,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                195,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(15, Short.MAX_VALUE)));
                panelDadosLayout.setVerticalGroup(
                                panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDadosLayout
                                                                .createSequentialGroup()
                                                                .addContainerGap(11, Short.MAX_VALUE)
                                                                .addComponent(imgDados,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                130,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnDados)
                                                                .addContainerGap()));

                panelPublicaciones.add(panelDados,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 230, 180));

                panelBingo.setBackground(new java.awt.Color(227, 199, 104));
                panelBingo.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)),
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255))));

                btnBingo.setBackground(new java.awt.Color(147, 128, 67));
                btnBingo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnBingo.setForeground(new java.awt.Color(255, 255, 255));
                btnBingo.setText("BINGO");
                btnBingo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBingoActionPerformed(evt);
                        }
                });

                imgBingo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bingo.png"))); // NOI18N
                imgBingo.setText("jLabel2");

                javax.swing.GroupLayout panelBingoLayout = new javax.swing.GroupLayout(panelBingo);
                panelBingo.setLayout(panelBingoLayout);
                panelBingoLayout.setHorizontalGroup(
                                panelBingoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panelBingoLayout.createSequentialGroup()
                                                                .addGroup(panelBingoLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(panelBingoLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(72, 72, 72)
                                                                                                .addComponent(btnBingo))
                                                                                .addGroup(panelBingoLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(17, 17, 17)
                                                                                                .addComponent(imgBingo,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                195,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(14, Short.MAX_VALUE)));
                panelBingoLayout.setVerticalGroup(
                                panelBingoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBingoLayout
                                                                .createSequentialGroup()
                                                                .addContainerGap(11, Short.MAX_VALUE)
                                                                .addComponent(imgBingo,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                130,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnBingo)
                                                                .addContainerGap()));

                panelPublicaciones.add(panelBingo,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 230, 180));

                scrollPublicaciones.setViewportView(panelPublicaciones);

                ventanaPrincipal.add(scrollPublicaciones,
                                new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 890, 480));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ventanaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ventanaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnBingoActionPerformed(java.awt.event.ActionEvent evt) {
                Bingo bingo = new Bingo();
                bingo.setVisible(true);
                this.setVisible(false);
        }

        private void btnTragaMonedasActionPerformed(java.awt.event.ActionEvent evt) {
                TragaMonedas tragaMonedas = new TragaMonedas();
                tragaMonedas.setVisible(true);
                this.setVisible(false);

        }

        private void btnPokerActionPerformed(java.awt.event.ActionEvent evt) {
                Poker poker = new Poker();
                poker.setVisible(true);
                this.setVisible(false);

        }

        private void btnBlackJackActionPerformed(java.awt.event.ActionEvent evt) {
                BlackJack blackJack = new BlackJack();
                blackJack.setVisible(true);
                this.setVisible(false);

        }

        private void btnRuletaActionPerformed(java.awt.event.ActionEvent evt) {
                Ruleta ruleta = new Ruleta();
                ruleta.setVisible(true);
                this.setVisible(false);

        }

        private void btnDadosActionPerformed(java.awt.event.ActionEvent evt) {
                Dados dados = new Dados();
                dados.setVisible(true);
                this.setVisible(false);

        }

        private void textosLabels() {
                imgVolver.setToolTipText("Salir");
                imgUsuario.setToolTipText("Usuario");
        }

        private void imgUsuarioMouseEntered(java.awt.event.MouseEvent evt) {
                CambiarIU.setImageLabel(imgUsuario, "src/img/usuarioHover.png");
        }

        private void imgUsuarioMouseExited(java.awt.event.MouseEvent evt) {
                CambiarIU.setImageLabel(imgUsuario, "src/img/usuario.png");
        }

        private void imgVolverMouseEntered(java.awt.event.MouseEvent evt) {
                CambiarIU.setImageLabel(imgVolver, "src/img/volverHover.png");
        }

        private void imgVolverMouseExited(java.awt.event.MouseEvent evt) {
                CambiarIU.setImageLabel(imgVolver, "src/img/volver.png");
        }

        private void imgVolverMouseClicked(java.awt.event.MouseEvent evt) {
                Login login = new Login();
                login.setVisible(true);
                this.setVisible(false);
        }

        private void imgUsuarioMouseClicked(java.awt.event.MouseEvent evt) {
                PersonalProfile perfil = new PersonalProfile();
                perfil.setVisible(true);
                this.setVisible(false);
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                FlatMacDarkLaf.setup();
                EventQueue.invokeLater(() -> new Principal().setVisible(true));
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnBingo;
        private javax.swing.JButton btnBlackJack;
        private javax.swing.JButton btnDados;
        private javax.swing.JButton btnPoker;
        private javax.swing.JButton btnRuleta;
        private javax.swing.JButton btnTragaMonedas;
        private javax.swing.JLabel imgBingo;
        private javax.swing.JLabel imgBlackJack;
        private javax.swing.JLabel imgCasa;
        private javax.swing.JLabel imgDados;
        private javax.swing.JLabel imgMenuBar;
        private javax.swing.JLabel imgPoker;
        private javax.swing.JLabel imgRuleta;
        private javax.swing.JLabel imgTragaMonedas;
        private javax.swing.JLabel imgUsuario;
        private javax.swing.JLabel imgVolver;
        private javax.swing.JLabel lbJuegos;
        private javax.swing.JPanel panelBingo;
        private javax.swing.JPanel panelBlackJack;
        private javax.swing.JPanel panelDados;
        private javax.swing.JPanel panelMenu;
        private javax.swing.JPanel panelPoker;
        private javax.swing.JPanel panelPublicaciones;
        private javax.swing.JPanel panelRuleta;
        private javax.swing.JPanel panelTragaMonedas;
        private javax.swing.JScrollPane scrollPublicaciones;
        private javax.swing.JPanel ventanaPrincipal;
        // End of variables declaration//GEN-END:variables
}
