/*
 cSpell:ignore publicacion ubicacion operacion
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package servidorChatsCasinoRoyal;

import java.awt.Toolkit;

import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author tutaa
 */
public class VistaServidor extends javax.swing.JFrame {

	/**
	 * Creates new form Bingo
	 */
	Map<Integer, String> juegos = new HashMap<>();
	private int PORT;

	public VistaServidor(int PORT_JUEGO) {
		this.PORT = PORT_JUEGO;
		llenarJuegos();

		initComponents();
		this.setTitle("Servidor Chat - " + juegos.get(PORT));
		this.setResizable(false);
		this.setLocationRelativeTo(null);
		this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/icon.png")));
		taChatServidor.setEditable(false);

		startChatServer(PORT);
	}

	private void llenarJuegos() {

		juegos = new HashMap<>();
		juegos.put(1111, "Carrera");
		juegos.put(2222, "BlackJack");
		juegos.put(3333, "Poker");
		juegos.put(4444, "Ruleta");

	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		ventanaServidor = new javax.swing.JPanel();
		lbChat = new javax.swing.JLabel();
		scChatServidor = new javax.swing.JScrollPane();
		taChatServidor = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		ventanaServidor.setBackground(new java.awt.Color(27, 9, 5));
		ventanaServidor.setPreferredSize(new java.awt.Dimension(1080, 720));
		ventanaServidor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		lbChat.setFont(new java.awt.Font("Crabs", 1, 48)); // NOI18N
		lbChat.setForeground(new java.awt.Color(227, 199, 104));
		lbChat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lbChat.setText("Chat -");
		ventanaServidor.add(lbChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 490, -1));

		taChatServidor.setBackground(new java.awt.Color(36, 38, 41));
		taChatServidor.setColumns(20);
		taChatServidor.setForeground(new java.awt.Color(148, 161, 178));
		taChatServidor.setLineWrap(true);
		taChatServidor.setRows(5);
		taChatServidor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 199, 104)));
		scChatServidor.setViewportView(taChatServidor);

		ventanaServidor.add(scChatServidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 400, 450));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(ventanaServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 487,
								javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(ventanaServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 568,
								javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	private void startChatServer(int PORT) {
		lbChat.setText("Chat - " + juegos.get(PORT));
		new Thread(() -> new ChatServer(PORT, this)).start();
	}

	public void appendToChat(String message) {
		taChatServidor.append(message + "\n");
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel lbChat;
	private javax.swing.JScrollPane scChatServidor;
	private javax.swing.JTextArea taChatServidor;
	private javax.swing.JPanel ventanaServidor;
	// End of variables declaration//GEN-END:variables
}
