/*
 cSpell:ignore publicacion ubicacion operacion numeros tahoma
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.com.casinoRoyal.ui.views.games.ruleta;

import java.awt.Color;
import java.awt.Toolkit;


/**
 *
 * @author tutaa
 */
public class MostrarCasilla extends javax.swing.JFrame {

        /**
         * Creates new form MostrarCasilla
         * 
         * @param numero
	 * @param color
         */

        public MostrarCasilla(int numero, Color color) {
                initComponents();

                this.setTitle("Ruleta");
                this.setResizable(false);
                this.setLocationRelativeTo(null);

                this.setIconImage(Toolkit.getDefaultToolkit()
                                .getImage(getClass().getResource("/img/icon.png")));
                panelCasilla.setBackground(color);
                lbNumeroCasilla.setText(String.valueOf(numero));
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                ventanaMostrarCasilla = new javax.swing.JPanel();
                panelCasilla = new main.java.com.casinoRoyal.ui.components.PanelRound();
                lbNumeroCasilla = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                ventanaMostrarCasilla.setBackground(new java.awt.Color(27, 9, 5));
                ventanaMostrarCasilla.setPreferredSize(new java.awt.Dimension(1080, 720));
                ventanaMostrarCasilla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                panelCasilla.setBackground(new java.awt.Color(36, 38, 41));
                panelCasilla.setRoundBottomLeft(30);
                panelCasilla.setRoundBottomRight(30);
                panelCasilla.setRoundTopLeft(30);
                panelCasilla.setRoundTopRight(30);

                lbNumeroCasilla.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
                lbNumeroCasilla.setForeground(new java.awt.Color(255, 255, 255));
                lbNumeroCasilla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbNumeroCasilla.setText("-");

                javax.swing.GroupLayout panelCasillaLayout = new javax.swing.GroupLayout(panelCasilla);
                panelCasilla.setLayout(panelCasillaLayout);
                panelCasillaLayout.setHorizontalGroup(
                        panelCasillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbNumeroCasilla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                );
                panelCasillaLayout.setVerticalGroup(
                        panelCasillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbNumeroCasilla, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                );

                ventanaMostrarCasilla.add(panelCasilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 110));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ventanaMostrarCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ventanaMostrarCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel lbNumeroCasilla;
        private main.java.com.casinoRoyal.ui.components.PanelRound panelCasilla;
        private javax.swing.JPanel ventanaMostrarCasilla;
        // End of variables declaration//GEN-END:variables
}
