/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screens.Profile;

/**
 *
 * @author lalaa
 */
public class PersonalTransaccion extends javax.swing.JFrame {

    /**
     * Creates new form PersonalTransaccion
     */
    public PersonalTransaccion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imgVolver = new javax.swing.JLabel();
        lbTransacciones = new javax.swing.JLabel();
        tbContenidoTransacciones = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(27, 9, 5));

        jPanel1.setBackground(new java.awt.Color(27, 9, 5));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver.png"))); // NOI18N
        imgVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imgVolverMouseExited(evt);
            }
        });
        jPanel1.add(imgVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lbTransacciones.setFont(new java.awt.Font("Crabs", 1, 85)); // NOI18N
        lbTransacciones.setForeground(new java.awt.Color(227, 199, 104));
        lbTransacciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTransacciones.setText("Transacciones");
        jPanel1.add(lbTransacciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1080, -1));

        jTable1.setBackground(new java.awt.Color(36, 38, 41));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"20/10/2024", "400.000", "Deposito", "COMPLETADO"},
                {"20/10/2024", "100.000", "Bonificación", "EN PROCESO"},
                {"30/04/2024", "1'000.000", "Retiro", "FALLIDO"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Valor Transaccion", "Tipo Transaccion", "Estado transacción"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setGridColor(new java.awt.Color(255, 51, 51));
        jTable1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jTable1ComponentRemoved(evt);
            }
        });
        tbContenidoTransacciones.setViewportView(jTable1);

        jPanel1.add(tbContenidoTransacciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 980, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTable1ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1ComponentRemoved

    private void imgVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgVolverMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_imgVolverMouseClicked

    private void imgVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgVolverMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_imgVolverMouseEntered

    private void imgVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgVolverMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_imgVolverMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonalTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonalTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonalTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonalTransaccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbTransacciones;
    private javax.swing.JScrollPane tbContenidoTransacciones;
    // End of variables declaration//GEN-END:variables
}
