/*
 cSpell:ignore publicacion ubicacion operacion
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screens.Principal.Games;

import Code.ChatClient;
import Code.OperacionCRUD;
import Screens.Custom.CambiarIU;
import Screens.Login.Login;
import Screens.Principal.Principal;

import java.awt.EventQueue;
import java.awt.Toolkit;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;

import javax.swing.JOptionPane;

/**
 *
 * @author tutaa
 */
public class Bingo extends javax.swing.JFrame {

        /**
         * Creates new form Bingo
         */
        private ChatClient chatClient;

        public Bingo() {
                initComponents();

                this.setTitle("Bingo");
                this.setResizable(false);
                this.setLocationRelativeTo(null);

                this.setIconImage(Toolkit.getDefaultToolkit()
                                .getImage(getClass().getResource("/img/icon.png")));
                ingresarChat();
                taChatBingo.setEditable(false);
                ponerFondos();
        }

        private void ponerFondos() {
                try {
                        ArrayList<ArrayList<Object>> datos = OperacionCRUD.seleccionar(
                                        String.format("SELECT * FROM jugadores where jugador_id = %d",
                                                        Login.idUsuarioGuardar),
                                        new String[] { "fondos_jugador" });

                        CambiarIU.ponerTextoEtiqueta(lbPonerFondos, (datos.get(0).get(0) + " Fondos"));

                } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR",
                                        JOptionPane.ERROR_MESSAGE);

                }
        }

        private String obtenerNombre() {

                try {
                        ArrayList<ArrayList<Object>> datos = OperacionCRUD.seleccionar(
                                        String.format("SELECT * FROM jugadores where jugador_id = %d",
                                                        Login.idUsuarioGuardar),
                                        new String[] { "nombre_usuario" });

                        String[] nombreCompleto = ((String) datos.get(0).get(0)).split(" ");
                        String nombreApellido = "";
                        if (nombreCompleto.length <= 5 && nombreCompleto.length >= 3) {
                                nombreApellido = nombreCompleto[0] + " " + nombreCompleto[2];

                        } else if (nombreCompleto.length == 1) {
                                nombreApellido = nombreCompleto[0];
                        } else {
                                nombreApellido = nombreCompleto[0] + " " + nombreCompleto[1];
                        }

                        return nombreApellido;
                } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR",
                                        JOptionPane.ERROR_MESSAGE);
                }
                return "";
        }

        private void ingresarChat() {
                Thread chatThread = new Thread(() -> {
                        String nombre = obtenerNombre();
                        if (!nombre.isEmpty()) {
                                chatClient = new ChatClient(nombre, taChatBingo, taMensaje, imgEnviar, 1111);
                        } else {
                                System.out.println("No se pudo obtener el nombre del jugador.");
                        }
                });
                chatThread.start();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                ventanaBingo = new javax.swing.JPanel();
                imgVolver = new javax.swing.JLabel();
                lbBingo = new javax.swing.JLabel();
                lbPonerFondos = new javax.swing.JLabel();
                btnDepositar = new javax.swing.JButton();
                lbChat = new javax.swing.JLabel();
                scChatBingo = new javax.swing.JScrollPane();
                taChatBingo = new javax.swing.JTextArea();
                scMensaje = new javax.swing.JScrollPane();
                taMensaje = new javax.swing.JTextArea();
                imgEnviar = new javax.swing.JLabel();
                btnBingo = new javax.swing.JButton();
                btnApostar = new javax.swing.JButton();
                btnRetirarse = new javax.swing.JButton();
                pCarton = new javax.swing.JPanel();
                lbB = new javax.swing.JLabel();
                lbI = new javax.swing.JLabel();
                lbN = new javax.swing.JLabel();
                lbG = new javax.swing.JLabel();
                lbO = new javax.swing.JLabel();
                btnB1 = new javax.swing.JButton();
                btnI1 = new javax.swing.JButton();
                btnN1 = new javax.swing.JButton();
                btnG1 = new javax.swing.JButton();
                btnO1 = new javax.swing.JButton();
                btnB2 = new javax.swing.JButton();
                btnI2 = new javax.swing.JButton();
                btnN2 = new javax.swing.JButton();
                btnG2 = new javax.swing.JButton();
                btnO2 = new javax.swing.JButton();
                btnB3 = new javax.swing.JButton();
                btnI3 = new javax.swing.JButton();
                btnN3 = new javax.swing.JButton();
                btnG3 = new javax.swing.JButton();
                btnO3 = new javax.swing.JButton();
                btnB4 = new javax.swing.JButton();
                btnI4 = new javax.swing.JButton();
                btnN4 = new javax.swing.JButton();
                btnG4 = new javax.swing.JButton();
                btnO4 = new javax.swing.JButton();
                btnB5 = new javax.swing.JButton();
                btnI5 = new javax.swing.JButton();
                btnN5 = new javax.swing.JButton();
                btnG5 = new javax.swing.JButton();
                btnO5 = new javax.swing.JButton();
                pUltimoNumero = new javax.swing.JPanel();
                btnUltimoNumero = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                ventanaBingo.setBackground(new java.awt.Color(27, 9, 5));
                ventanaBingo.setPreferredSize(new java.awt.Dimension(1080, 720));
                ventanaBingo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                imgVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver.png"))); // NOI18N
                imgVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                imgVolver.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                imgVolverMouseClicked(evt);
                        }

                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                imgVolverMouseEntered(evt);
                        }

                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                imgVolverMouseExited(evt);
                        }
                });
                ventanaBingo.add(imgVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

                lbBingo.setFont(new java.awt.Font("Crabs", 1, 100)); // NOI18N
                lbBingo.setForeground(new java.awt.Color(227, 199, 104));
                lbBingo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbBingo.setText("Bingo");
                ventanaBingo.add(lbBingo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1080, -1));

                lbPonerFondos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                lbPonerFondos.setForeground(new java.awt.Color(148, 161, 178));
                lbPonerFondos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                lbPonerFondos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondos.png"))); // NOI18N
                lbPonerFondos.setText("-");
                ventanaBingo.add(lbPonerFondos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1050, -1));

                btnDepositar.setBackground(new java.awt.Color(147, 128, 67));
                btnDepositar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                btnDepositar.setForeground(new java.awt.Color(255, 255, 254));
                btnDepositar.setText("Depositar");
                btnDepositar.setActionCommand("Ingresar");
                btnDepositar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnDepositar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDepositarActionPerformed(evt);
                        }
                });
                ventanaBingo.add(btnDepositar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 50, -1, -1));

                lbChat.setFont(new java.awt.Font("Crabs", 1, 48)); // NOI18N
                lbChat.setForeground(new java.awt.Color(227, 199, 104));
                lbChat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbChat.setText("Chat");
                ventanaBingo.add(lbChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 310, 220, -1));

                taChatBingo.setBackground(new java.awt.Color(36, 38, 41));
                taChatBingo.setColumns(20);
                taChatBingo.setForeground(new java.awt.Color(148, 161, 178));
                taChatBingo.setLineWrap(true);
                taChatBingo.setRows(5);
                taChatBingo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 199, 104)));
                scChatBingo.setViewportView(taChatBingo);

                ventanaBingo.add(scChatBingo, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 370, -1, 260));

                taMensaje.setBackground(new java.awt.Color(36, 38, 41));
                taMensaje.setColumns(20);
                taMensaje.setForeground(new java.awt.Color(148, 161, 178));
                taMensaje.setLineWrap(true);
                taMensaje.setRows(2);
                taMensaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 199, 104)));
                scMensaje.setViewportView(taMensaje);

                ventanaBingo.add(scMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 650, 180, 50));

                imgEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/enviar.png"))); // NOI18N
                imgEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                imgEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                imgEnviarMouseClicked(evt);
                        }

                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                imgEnviarMouseEntered(evt);
                        }

                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                imgEnviarMouseExited(evt);
                        }
                });
                ventanaBingo.add(imgEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 650, 40, 40));

                btnBingo.setBackground(new java.awt.Color(0, 153, 0));
                btnBingo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                btnBingo.setForeground(new java.awt.Color(255, 255, 254));
                btnBingo.setText("BINGO!!");
                btnBingo.setActionCommand("Ingresar");
                btnBingo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnBingo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBingoActionPerformed(evt);
                        }
                });
                ventanaBingo.add(btnBingo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 140, 50));

                btnApostar.setBackground(new java.awt.Color(147, 128, 67));
                btnApostar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                btnApostar.setForeground(new java.awt.Color(255, 255, 254));
                btnApostar.setText("Apostar");
                btnApostar.setActionCommand("Ingresar");
                btnApostar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnApostar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnApostarActionPerformed(evt);
                        }
                });
                ventanaBingo.add(btnApostar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 140, -1));

                btnRetirarse.setBackground(new java.awt.Color(147, 128, 67));
                btnRetirarse.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                btnRetirarse.setForeground(new java.awt.Color(255, 255, 254));
                btnRetirarse.setText("Retirarse");
                btnRetirarse.setActionCommand("Ingresar");
                btnRetirarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnRetirarse.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRetirarseActionPerformed(evt);
                        }
                });
                ventanaBingo.add(btnRetirarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 140, -1));

                pCarton.setBackground(new java.awt.Color(27, 9, 5));
                pCarton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 199, 104)));
                pCarton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lbB.setFont(new java.awt.Font("Crabs", 1, 90)); // NOI18N
                lbB.setForeground(new java.awt.Color(227, 199, 104));
                lbB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbB.setText("B");
                lbB.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                pCarton.add(lbB, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 10, 280, 100));

                lbI.setFont(new java.awt.Font("Crabs", 1, 90)); // NOI18N
                lbI.setForeground(new java.awt.Color(227, 199, 104));
                lbI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbI.setText("I");
                lbI.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                pCarton.add(lbI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 100));

                lbN.setFont(new java.awt.Font("Crabs", 1, 90)); // NOI18N
                lbN.setForeground(new java.awt.Color(227, 199, 104));
                lbN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbN.setText("N");
                lbN.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                pCarton.add(lbN, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 280, 100));

                lbG.setFont(new java.awt.Font("Crabs", 1, 90)); // NOI18N
                lbG.setForeground(new java.awt.Color(227, 199, 104));
                lbG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbG.setText("G");
                lbG.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                pCarton.add(lbG, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 280, 100));

                lbO.setFont(new java.awt.Font("Crabs", 1, 90)); // NOI18N
                lbO.setForeground(new java.awt.Color(227, 199, 104));
                lbO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbO.setText("O");
                lbO.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                pCarton.add(lbO, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 280, 100));

                btnB1.setBackground(new java.awt.Color(36, 38, 41));
                btnB1.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
                btnB1.setForeground(new java.awt.Color(148, 161, 178));
                btnB1.setText("1");
                btnB1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnB1ActionPerformed(evt);
                        }
                });
                pCarton.add(btnB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 82, 71));

                btnI1.setBackground(new java.awt.Color(36, 38, 41));
                btnI1.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
                btnI1.setForeground(new java.awt.Color(148, 161, 178));
                btnI1.setText("4");
                btnI1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnI1ActionPerformed(evt);
                        }
                });
                pCarton.add(btnI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 82, 71));

                btnN1.setBackground(new java.awt.Color(36, 38, 41));
                btnN1.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
                btnN1.setForeground(new java.awt.Color(148, 161, 178));
                btnN1.setText("55");
                btnN1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnN1ActionPerformed(evt);
                        }
                });
                pCarton.add(btnN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 82, 71));

                btnG1.setBackground(new java.awt.Color(36, 38, 41));
                btnG1.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
                btnG1.setForeground(new java.awt.Color(148, 161, 178));
                btnG1.setText("45");
                btnG1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnG1ActionPerformed(evt);
                        }
                });
                pCarton.add(btnG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 82, 71));

                btnO1.setBackground(new java.awt.Color(36, 38, 41));
                btnO1.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
                btnO1.setForeground(new java.awt.Color(148, 161, 178));
                btnO1.setText("45");
                btnO1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnO1ActionPerformed(evt);
                        }
                });
                pCarton.add(btnO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 82, 71));

                btnB2.setBackground(new java.awt.Color(36, 38, 41));
                btnB2.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
                btnB2.setForeground(new java.awt.Color(148, 161, 178));
                btnB2.setText("1");
                btnB2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnB2ActionPerformed(evt);
                        }
                });
                pCarton.add(btnB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 82, 71));

                btnI2.setBackground(new java.awt.Color(36, 38, 41));
                btnI2.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
                btnI2.setForeground(new java.awt.Color(148, 161, 178));
                btnI2.setText("45");
                btnI2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnI2ActionPerformed(evt);
                        }
                });
                pCarton.add(btnI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 82, 71));

                btnN2.setBackground(new java.awt.Color(36, 38, 41));
                btnN2.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
                btnN2.setForeground(new java.awt.Color(148, 161, 178));
                btnN2.setText("45");
                btnN2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnN2ActionPerformed(evt);
                        }
                });
                pCarton.add(btnN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 82, 71));

                btnG2.setBackground(new java.awt.Color(36, 38, 41));
                btnG2.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
                btnG2.setForeground(new java.awt.Color(148, 161, 178));
                btnG2.setText("45");
                btnG2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnG2ActionPerformed(evt);
                        }
                });
                pCarton.add(btnG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 82, 71));

                btnO2.setBackground(new java.awt.Color(36, 38, 41));
                btnO2.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
                btnO2.setForeground(new java.awt.Color(148, 161, 178));
                btnO2.setText("45");
                btnO2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnO2ActionPerformed(evt);
                        }
                });
                pCarton.add(btnO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 82, 71));

                btnB3.setBackground(new java.awt.Color(36, 38, 41));
                btnB3.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
                btnB3.setForeground(new java.awt.Color(148, 161, 178));
                btnB3.setText("1");
                btnB3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnB3ActionPerformed(evt);
                        }
                });
                pCarton.add(btnB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 82, 71));

                btnI3.setBackground(new java.awt.Color(36, 38, 41));
                btnI3.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
                btnI3.setForeground(new java.awt.Color(148, 161, 178));
                btnI3.setText("45");
                btnI3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnI3ActionPerformed(evt);
                        }
                });
                pCarton.add(btnI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 82, 71));

                btnN3.setBackground(new java.awt.Color(36, 38, 41));
                btnN3.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
                btnN3.setForeground(new java.awt.Color(148, 161, 178));
                btnN3.setText("45");
                btnN3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnN3ActionPerformed(evt);
                        }
                });
                pCarton.add(btnN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 82, 71));

                btnG3.setBackground(new java.awt.Color(36, 38, 41));
                btnG3.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
                btnG3.setForeground(new java.awt.Color(148, 161, 178));
                btnG3.setText("45");
                btnG3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnG3ActionPerformed(evt);
                        }
                });
                pCarton.add(btnG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 82, 71));

                btnO3.setBackground(new java.awt.Color(36, 38, 41));
                btnO3.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
                btnO3.setForeground(new java.awt.Color(148, 161, 178));
                btnO3.setText("45");
                btnO3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnO3ActionPerformed(evt);
                        }
                });
                pCarton.add(btnO3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 82, 71));

                btnB4.setBackground(new java.awt.Color(36, 38, 41));
                btnB4.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
                btnB4.setForeground(new java.awt.Color(148, 161, 178));
                btnB4.setText("1");
                btnB4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnB4ActionPerformed(evt);
                        }
                });
                pCarton.add(btnB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 82, 71));

                btnI4.setBackground(new java.awt.Color(36, 38, 41));
                btnI4.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
                btnI4.setForeground(new java.awt.Color(148, 161, 178));
                btnI4.setText("45");
                btnI4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnI4ActionPerformed(evt);
                        }
                });
                pCarton.add(btnI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 82, 71));

                btnN4.setBackground(new java.awt.Color(36, 38, 41));
                btnN4.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
                btnN4.setForeground(new java.awt.Color(148, 161, 178));
                btnN4.setText("45");
                btnN4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnN4ActionPerformed(evt);
                        }
                });
                pCarton.add(btnN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 82, 71));

                btnG4.setBackground(new java.awt.Color(36, 38, 41));
                btnG4.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
                btnG4.setForeground(new java.awt.Color(148, 161, 178));
                btnG4.setText("45");
                btnG4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnG4ActionPerformed(evt);
                        }
                });
                pCarton.add(btnG4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 82, 71));

                btnO4.setBackground(new java.awt.Color(36, 38, 41));
                btnO4.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
                btnO4.setForeground(new java.awt.Color(148, 161, 178));
                btnO4.setText("45");
                btnO4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnO4ActionPerformed(evt);
                        }
                });
                pCarton.add(btnO4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 82, 71));

                btnB5.setBackground(new java.awt.Color(36, 38, 41));
                btnB5.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
                btnB5.setForeground(new java.awt.Color(148, 161, 178));
                btnB5.setText("1");
                btnB5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnB5ActionPerformed(evt);
                        }
                });
                pCarton.add(btnB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 82, 71));

                btnI5.setBackground(new java.awt.Color(36, 38, 41));
                btnI5.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
                btnI5.setForeground(new java.awt.Color(148, 161, 178));
                btnI5.setText("45");
                btnI5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnI5ActionPerformed(evt);
                        }
                });
                pCarton.add(btnI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 82, 71));

                btnN5.setBackground(new java.awt.Color(36, 38, 41));
                btnN5.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
                btnN5.setForeground(new java.awt.Color(148, 161, 178));
                btnN5.setText("45");
                btnN5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnN5ActionPerformed(evt);
                        }
                });
                pCarton.add(btnN5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 82, 71));

                btnG5.setBackground(new java.awt.Color(36, 38, 41));
                btnG5.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
                btnG5.setForeground(new java.awt.Color(148, 161, 178));
                btnG5.setText("45");
                btnG5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnG5ActionPerformed(evt);
                        }
                });
                pCarton.add(btnG5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 82, 71));

                btnO5.setBackground(new java.awt.Color(36, 38, 41));
                btnO5.setFont(new java.awt.Font("Segoe UI", 0, 45)); // NOI18N
                btnO5.setForeground(new java.awt.Color(148, 161, 178));
                btnO5.setText("45");
                btnO5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnO5ActionPerformed(evt);
                        }
                });
                pCarton.add(btnO5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 82, 71));

                ventanaBingo.add(pCarton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 500, 560));

                pUltimoNumero.setBackground(new java.awt.Color(27, 9, 5));
                pUltimoNumero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 199, 104)));

                btnUltimoNumero.setBackground(new java.awt.Color(36, 38, 41));
                btnUltimoNumero.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
                btnUltimoNumero.setForeground(new java.awt.Color(148, 161, 178));
                btnUltimoNumero.setText("45");
                btnUltimoNumero.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnUltimoNumeroActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout pUltimoNumeroLayout = new javax.swing.GroupLayout(pUltimoNumero);
                pUltimoNumero.setLayout(pUltimoNumeroLayout);
                pUltimoNumeroLayout.setHorizontalGroup(
                                pUltimoNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 198, Short.MAX_VALUE)
                                                .addGroup(pUltimoNumeroLayout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(pUltimoNumeroLayout.createSequentialGroup()
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addComponent(btnUltimoNumero)
                                                                                .addGap(0, 0, Short.MAX_VALUE))));
                pUltimoNumeroLayout.setVerticalGroup(
                                pUltimoNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 138, Short.MAX_VALUE)
                                                .addGroup(pUltimoNumeroLayout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(pUltimoNumeroLayout.createSequentialGroup()
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addComponent(btnUltimoNumero)
                                                                                .addGap(0, 0, Short.MAX_VALUE))));

                ventanaBingo.add(pUltimoNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 130, 200, 140));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ventanaBingo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ventanaBingo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnRetirarseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRetirarseActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnRetirarseActionPerformed

        private void btnBingoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBingoActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnBingoActionPerformed

        private void btnApostarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnApostarActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnApostarActionPerformed

        private void btnO1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnO1ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnO1ActionPerformed

        private void btnB1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnB1ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnB1ActionPerformed

        private void btnI1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnI1ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnI1ActionPerformed

        private void btnN1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnN1ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnN1ActionPerformed

        private void btnG1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnG1ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnG1ActionPerformed

        private void btnUltimoNumeroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUltimoNumeroActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnUltimoNumeroActionPerformed

        private void btnB2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnB2ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnB2ActionPerformed

        private void btnI2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnI2ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnI2ActionPerformed

        private void btnN2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnN2ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnN2ActionPerformed

        private void btnG2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnG2ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnG2ActionPerformed

        private void btnO2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnO2ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnO2ActionPerformed

        private void btnB3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnB3ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnB3ActionPerformed

        private void btnI3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnI3ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnI3ActionPerformed

        private void btnN3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnN3ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnN3ActionPerformed

        private void btnG3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnG3ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnG3ActionPerformed

        private void btnO3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnO3ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnO3ActionPerformed

        private void btnB4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnB4ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnB4ActionPerformed

        private void btnI4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnI4ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnI4ActionPerformed

        private void btnN4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnN4ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnN4ActionPerformed

        private void btnG4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnG4ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnG4ActionPerformed

        private void btnO4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnO4ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnO4ActionPerformed

        private void btnB5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnB5ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnB5ActionPerformed

        private void btnI5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnI5ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnI5ActionPerformed

        private void btnN5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnN5ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnN5ActionPerformed

        private void btnG5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnG5ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnG5ActionPerformed

        private void btnO5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnO5ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnO5ActionPerformed

        private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDepositarActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnDepositarActionPerformed

        private void imgEnviarMouseClicked(java.awt.event.MouseEvent evt) {

        }

        private void imgEnviarMouseEntered(java.awt.event.MouseEvent evt) {
                CambiarIU.setImageLabel(imgEnviar, "src/img/enviarHover.png");

        }

        private void imgEnviarMouseExited(java.awt.event.MouseEvent evt) {
                CambiarIU.setImageLabel(imgEnviar, "src/img/enviar.png");

        }

        private void imgVolverMouseEntered(java.awt.event.MouseEvent evt) {
                CambiarIU.setImageLabel(imgVolver, "src/img/volverHover.png");
        }

        private void imgVolverMouseExited(java.awt.event.MouseEvent evt) {
                CambiarIU.setImageLabel(imgVolver, "src/img/volver.png");
        }

        private void imgVolverMouseClicked(java.awt.event.MouseEvent evt) {
                if (chatClient != null) {
                        chatClient.close();
                } else {
                        System.out.println("El cliente de chat no está inicializado.");
                }
                Principal principal = new Principal();
                principal.setVisible(true);
                this.setVisible(false);
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                FlatMacDarkLaf.setup();
                EventQueue.invokeLater(() -> new Bingo().setVisible(true));
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnApostar;
        private javax.swing.JButton btnB1;
        private javax.swing.JButton btnB2;
        private javax.swing.JButton btnB3;
        private javax.swing.JButton btnB4;
        private javax.swing.JButton btnB5;
        private javax.swing.JButton btnBingo;
        private javax.swing.JButton btnDepositar;
        private javax.swing.JButton btnG1;
        private javax.swing.JButton btnG2;
        private javax.swing.JButton btnG3;
        private javax.swing.JButton btnG4;
        private javax.swing.JButton btnG5;
        private javax.swing.JButton btnI1;
        private javax.swing.JButton btnI2;
        private javax.swing.JButton btnI3;
        private javax.swing.JButton btnI4;
        private javax.swing.JButton btnI5;
        private javax.swing.JButton btnN1;
        private javax.swing.JButton btnN2;
        private javax.swing.JButton btnN3;
        private javax.swing.JButton btnN4;
        private javax.swing.JButton btnN5;
        private javax.swing.JButton btnO1;
        private javax.swing.JButton btnO2;
        private javax.swing.JButton btnO3;
        private javax.swing.JButton btnO4;
        private javax.swing.JButton btnO5;
        private javax.swing.JButton btnRetirarse;
        private javax.swing.JButton btnUltimoNumero;
        private javax.swing.JLabel imgEnviar;
        private javax.swing.JLabel imgVolver;
        private javax.swing.JLabel lbB;
        private javax.swing.JLabel lbBingo;
        private javax.swing.JLabel lbChat;
        private javax.swing.JLabel lbG;
        private javax.swing.JLabel lbI;
        private javax.swing.JLabel lbN;
        private javax.swing.JLabel lbO;
        private javax.swing.JLabel lbPonerFondos;
        private javax.swing.JPanel pCarton;
        private javax.swing.JPanel pUltimoNumero;
        private javax.swing.JScrollPane scChatBingo;
        private javax.swing.JScrollPane scMensaje;
        private javax.swing.JTextArea taChatBingo;
        private javax.swing.JTextArea taMensaje;
        private javax.swing.JPanel ventanaBingo;
        // End of variables declaration//GEN-END:variables
}
